export { default as Navbar } from './navbar'
export { default as Routes } from './routes'
export { default as Landing } from './landing'
export { default as About } from './about'
export { default as Projects } from './projects'
export { default as Music } from './music'
